import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

//Java program to calculate MD5,SHA-1,SHA-256 and SHA-512 hash values
public class JavaHash {
    //Function to calculate the Cryptographic hash value of an input String and the provided Digest algorithm
    public static String getCryptoHash(String input, String algorithm) {
        try {
            //MessageDigest classes Static getInstance method is called with MD5 hashing
            MessageDigest msgDigest = MessageDigest.getInstance(algorithm);

            //digest() method is called to calculate message digest of the input
            //digest() return array of byte.
            byte[] inputDigest = msgDigest.digest(input.getBytes());

            // Convert byte array into signum representation
            // BigInteger class is used, to convert the resultant byte array into its signum representation
            BigInteger inputDigestBigInt = new BigInteger(1, inputDigest);

            // Convert the input digest into hex value
            String hashtext = inputDigestBigInt.toString(16);

            //Add preceding 0's to pad the hashtext to make it 32 bit
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        }
        // Catch block to handle the scenarios when an unsupported message digest algorithm is provided.
        catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    //Driver Code
    public static void main(String args[]) throws NoSuchAlgorithmException {
        String inputText = "Input message";
        System.out.println("HashCode Generated by MD5 is: " + getCryptoHash(inputText, "MD5"));
        System.out.println("HashCode Generated by SHA-1 is: " + getCryptoHash(inputText, "SHA-1"));
        System.out.println("HashCode Generated by SHA-256 is: " + getCryptoHash(inputText, "SHA-256"));
        System.out.println("HashCode Generated by SHA-512 is: " + getCryptoHash(inputText, "SHA-512"));
    }

}